version: 1.2
workflows:
   - name: allele_freq
     subclass: CWL
     publish: true
     primaryDescriptorPath: /tools/allele_freq.cwl
     testParameterFiles:
         - /tools/test/allele_freq.test.json
